# Generated by Django 6.0.4 on 2026-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
